# kubectl -n security-tools apply -f sonarqube-pvc.yaml
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: security-tools
  name: sonarqube-data-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: security-tools
  name: sonarqube-extension-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: security-tools
  name: sonarqube-logs-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi