# kubectl -n exercise apply -f deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: own-your-stack
  labels:
    app: own-your-stack
spec:
  selector:
    matchLabels:
      app: own-your-stack
  template:
    metadata:
      labels:
        app: own-your-stack
    spec:
      containers:
        - name: own-your-stack
          image: glendmaatita/own-your-stack:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: 100Mi
              cpu: 50m
            limits:
              memory: 200Mi
              cpu: 100m
      restartPolicy: Always