# Source: https://github.com/janikgar/boundary-chart
# helm -n observability install boundary janikgar/boundary -f values.yaml

# boundary authenticate-method set-primary -id=password -scope-id=global
# boundary authenticate password -login-name admin -password Oz75cjSm8XV4F8FJQDqf

replicaCount: 1

publicAddress: 192.168.0.1
publicPort: 80

database:
  url: "172.25.0.3"
  port: 5432
  dbName: boundary
  ssl: false
  username: ""
  password: ""

service:
  - type: ClusterIP
    ports:
      - name: api
        number: 9200
      - name: cluster
        number: 9201
    annotations:
      boundary: "shared"

vault:
  enabled: false

ingress:
  enabled: false