# kubectl -n exercise apply -f configmap.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: exercise-app-cm
data:
  APP_NAME: "Exercise App"
  AUTHOR: "OnXP"
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  app.conf: |
    [options]
    addons_path = /mnt/extra-addons
    data_dir = /var/lib/data
    max_conn = 100