# kubectl -n exercise apply -f deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: own-your-stack
  labels:
    app: own-your-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: own-your-stack

  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 1
  #     maxUnavailable: 1
  template:
    metadata:
      labels:
        app: own-your-stack
    spec:
      # initContainers:
      #   - name: init-curl
      #     image: curlimages/curl
      #     imagePullPolicy: Always 
      #     command:
      #     - curl
      #     - -v
      #     - https://onxp.net
      containers:
        - name: own-your-stack
          image: glendmaatita/own-your-stack:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: 100Mi
              cpu: 50m
            limits:
              memory: 200Mi
              cpu: 100m
          
          # env
          env:
          - name: APP_URL
            value: https://own-your-stack.bootcamp.onxp.net
          - name: APP_KEY
            value: randomlongstring
          
          # health-check
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            successThreshold: 1
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            successThreshold: 1
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 1
            
          # envFrom:
          #   - configMapRef:
          #       name: own-your-stack-cm
          #   - secretRef:
          #       name: own-your-stack-secret
      restartPolicy: Always
      imagePullSecrets:
        - name: docker-secret