# https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough
# kubectl -n exercise apply -f hpa.yaml
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: own-your-stack
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: own-your-stack
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

  # - type: Pods
  #   pods:
  #     metric:
  #       name: packets-per-second
  #     targetAverageValue: 1000
  # - type: Object
  #   object:
  #     metric:
  #       name: requests-per-second
  #     describedObject:
  #       apiVersion: networking.k8s.io/v1
  #       kind: Ingress
  #       name: main-route
  #     target:
  #       kind: Value
  #       value: 10000
---