# kubectl -n exercise apply -f secret.yaml
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: exercise-app-secret
data:
  DB_CONNECTION: "cGdzcWw=" # pgsql
  DB_HOST: "cGdib3VuY2VyLW1hc3Rlci5leGVyY2lzZQ==" # pgbouncer-master.exercise
  DB_USERNAME: "YWRtaW4=" # admin
  DB_PASSWORD: "c3VwM3JzM2NyM3Q=" # sup3rs3cr3t
  DB_NAME: "ZXhlcmNpc2UtYXBw" # exercise-app
  DB_PORT: "NTQzMg==" # 5432
  
  # if using MySQL
  # DB_CONNECTION: "bXlzcWw=" # mysql
  # DB_NAME: "ZXhlcmNpc2UtYXBw"
  # DB_HOST: "cHJveHlzcWwucHJveHlzcWw=" # proxysql.proxysql
  # DB_USERNAME: "WVdSdGFXND0=" # admin
  # DB_PASSWORD: "c3VwM3JzM2NyM3Q="
  # DB_PORT: "NjAzMw==" #6033
---