# kubectl -n database apply -f deployment.yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgpool
spec:
  selector:
    matchLabels:
      app: pgpool
  template:
    metadata:
      labels:
        app: pgpool
    spec:
      containers:
      - name: pgpool
        image: pgpool/pgpool
        env:
        - name: POSTGRES_USERNAME
          value: onxp
        - name: POSTGRES_PASSWORD
          value: onxpsecret
        - name: PGPOOL_PASSWORD_ENCRYPTION_METHOD
          value: "scram-sha-256"
        - name: PGPOOL_ENABLE_POOL_PASSWD
          value: "true"
        - name: PGPOOL_SKIP_PASSWORD_ENCRYPTION
          value: "false"
        volumeMounts:
        - name: pgpool-config
          mountPath: /config
      volumes:
      - name: pgpool-config
        configMap:
          name: pgpool-config
---
apiVersion: v1
kind: Service
metadata:
  name: pgpool
spec:
  selector:
    app: pgpool
  ports:
  - name: pgpool-port
    protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgpool-config
  labels:
    app: pgpool-config
data:
  pgpool.conf: |-
    listen_addresses = '*'
    port = 5432
    socket_dir = '/var/run/pgpool'
    pcp_listen_addresses = '*'
    pcp_port = 9898
    pcp_socket_dir = '/var/run/pgpool'
    backend_hostname0 = 'postgresql-primary.database'
    backend_port0 = 5432
    backend_weight0 = 0
    backend_flag0 = 'ALWAYS_PRIMARY|DISALLOW_TO_FAILOVER'
    backend_hostname1 = 'postgresql-onxp-postgresql-read-replica.database'
    backend_port1 = 5432
    backend_weight1 = 1
    backend_flag1 = 'DISALLOW_TO_FAILOVER'
    # backend_hostname1 = '<Slave-2 DB IP>, pgbouncer-master.exercise'
    # backend_port1 = 5432
    # backend_weight1 = 1
    # backend_flag1 = 'DISALLOW_TO_FAILOVER'
    health_check_period = 10
    health_check_user = 'onxp'
    health_check_password = 'onxpsecret'
    health_check_database = 'example_db'
    master_slave_mode = on
    backend_clustering_mode = 'streaming_replication'
    num_init_children = 5000
    max_pool = 4
    child_life_time = 300
    child_max_connections = 0
    connection_life_time = 0
    client_idle_limit = 0
    connection_cache = on
    load_balance_mode = on
    ssl = off
    enable_pool_hba = on
    failover_on_backend_error = off
    log_min_messages = warning
    sr_check_period = 10
    sr_check_user = 'onxp'
    sr_check_password = 'onxpsecret'
    sr_check_database = 'example_db'
    log_destination = 'stderr'
    black_function_list = 'nextval,setval,lastval,currval'
    statement_level_load_balance = on
    disable_load_balance_on_write = trans_transaction
    relcache_size =1024
    log_per_node_statement = off
    log_disconnections = off