---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercise-app
  labels:
    app: exercise-app
spec:
  selector:
    matchLabels:
      app: exercise-app
  template:
    spec:
      containers:
        - image: glendmaatita/exercise-app:latest
          name: exercise-app
          resources:
            requests:
              memory: 20Mi
              cpu: 10m
            limits:
              memory: 30Mi
              cpu: 15m
