# ~$ gcloud iam service-accounts add-iam-policy-binding \
#   --role roles/iam.workloadIdentityUser \
#   --member "serviceAccount:mashanz-software-engineering.svc.id.goog[exercise/cloudsql-exercise]" \
#   cloudsql-onxp@mashanz-software-engineering.iam.gserviceaccount.com
# ```
# 4. Annotate the KSA to tie it with GSA
# ```
# ~$ kubectl annotate serviceaccount \
#   --namespace exercise \
#   cloudsql-exercise \
#   iam.gke.io/gcp-service-account=cloudsql-onxp@mashanz-software-engineering.iam.gserviceaccount.com

# kubectl -n exercise apply -f sa.yaml

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onxp-exercise-sa
  namespace: exercise

# execute after service acount and secret are created
# secrets:
#   - name: onxp-exercise-sa-secret

---
apiVersion: v1
kind: Secret
metadata:
  name: onxp-exercise-sa-secret
  annotations:
    kubernetes.io/service-account.name: onxp-exercise-sa
type: "kubernetes.io/service-account-token"

