---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: own-your-stack
  labels:
    app: own-your-stack
spec:
  selector:
    matchLabels:
      app: own-your-stack
  template:
    metadata:
      labels:
        app: own-your-stack
    spec:
      containers:
        - name: own-your-stack
          image: glendmaatita/own-your-stack:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: 30Mi
              cpu: 30m
            limits:
              memory: 40Mi
              cpu: 40m
      restartPolicy: Always
      imagePullSecrets:
        - name: docker-secret

---
apiVersion: batch/v1
kind: Job
metadata:
  name: argocd-sync-oys-succeeded
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
        - name: discord-notification
          image: curlimages/curl
          command:
            - curl
            - -v
            - GET
            - https://onxp.net
      restartPolicy: Never
  backoffLimit: 2
---
apiVersion: batch/v1
kind: Job
metadata:
  name: argocd-sync-oys-failed
  annotations:
    argocd.argoproj.io/hook: SyncFail
spec:
  template:
    spec:
      containers:
        - name: discord-notification
          image: curlimages/curl
          command:
            - curl
            - -v
            - GET
            - https://onxp.net
      restartPolicy: Never
  backoffLimit: 2
---
apiVersion: batch/v1
kind: Job
metadata:
  name: argocd-sync-oys-prepare
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: discord-notification
          image: curlimages/curl
          command:
            - curl
            - -v
            - GET
            - https://onxp.net
      restartPolicy: Never
  backoffLimit: 2

