---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: own-your-stack
  labels:
    app: own-your-stack
spec:
  selector:
    matchLabels:
      app: own-your-stack
  template:
    metadata:
      labels:
        app: own-your-stack
    spec:
      containers:
        - name: own-your-stack
          image: glendmaatita/own-your-stack:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: own-your-stack-config
          resources:
            requests:
              memory: 100Mi
              cpu: 50m
            limits:
              memory: 200Mi
              cpu: 100m
      restartPolicy: Always
      imagePullSecrets:
        - name: pull-secret

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: own-your-stack
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: own-your-stack
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: own-your-stack
  labels:
    app: own-your-stack
spec:
  selector:
    app: own-your-stack
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: own-your-stack
  annotations:
    kubernetes.io/ingress.class: public
    cert-manager.io/cluster-issuer: letsencrypt-issuer
spec:
  rules:
    - host: own-your-stack-staging.bootcamp.onxp.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: own-your-stack
                port: 
                  number: 80
  tls:
    - hosts:
        - own-your-stack-staging.bootcamp.onxp.net
      secretName: tls-secret-own-your-stack
---
