# kubectl -n elastic-system apply -f hostpath-pvc.yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hostpath-elasticsearch-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      type: hostpath-elasticsearch
