# kubectl -n exercise apply -f hostpath-pvc.yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hostpath-exercise-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      type: hostpath-exercise
