# kubectl -n exercise apply -f docker-secret.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImIyNTRjRzVsZERwelpXTnlaWFE9IgoJCX0KICB9Cn0=
type: kubernetes.io/dockerconfigjson