# helm repo add bitnami https://charts.bitnami.com/bitnami
# helm install postgresql -f pg-values.yml bitnami/postgresql -n exercise
image:
  tag: 13.13.0

auth:
  enablePostgresUser: true
  postgresPassword: "onxpsecret"
  username: "onxp"
  password: "onxpsecret"
  database: "example_db"

primary:
  persistence:
    enabled: true
    existingClaim: "postgresql-pvc"

volumePermissions:
  enabled: true

initdbScripts:
  init_db.sql: |
    CREATE DATABASE own-your-stack;