# kubectl -n exercise apply -f pg-volume.yml
# dynamic persistent volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi