---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: own-your-stack
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: own-your-stack
  minReplicas: 1
  maxReplicas: 5
---