kind: Kustomization
resources:
  - ../../base
  # use it when you don't want to separate resources
patches:
  # - manifests.yml
  - path: deployment.yaml
  - path: ingress.yaml
  - path: hpa.yaml
  
namespace: exercise-production
