# kubectl -n observability apply -f nfs.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server-grafana
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server-grafana
  template:
    metadata:
      labels:
        role: nfs-server-grafana
    spec:
      containers:
      - name: nfs-server-grafana
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: nfs-pvc
      volumes:
        - name: nfs-pvc
          gcePersistentDisk:
            pdName: storage-grafana-jaeger
            fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server-grafana
  namespace: observability
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server-grafana

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server-grafana.observability.svc.cluster.local
    path: "/"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-pvc
  namespace: observability
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: grafana-pv
  resources:
    requests:
      storage: 10Gi