# helm repo add bitnami https://charts.bitnami.com/bitnami
# helm repo update
# install: helm install redis bitnami/redis -n exercise -f values.yaml
# upgrade: helm upgrade redis bitnami/redis -n exercise -f values.yaml
# uninstall: helm uninstall redis -n exercise

# docs: https://github.com/bitnami/charts/tree/main/bitnami/redis
image:
  tag: 7.2
architecture: standalone
auth:
  enabled: false
  sentinel: false
master:
  persistence:
    enabled: false
usePassword: false
